import { boolean, date, index, jsonb, pgTable, primaryKey, text, timestamp, uuid } from "drizzle-orm/pg-core";
import { auditCycleStatusEnum, auditItemResultEnum, bookingStatusEnum, maintenancePriorityEnum, maintenanceStatusEnum, notificationTypeEnum } from "./enums";
import { assets } from "./assets";
import { departments, employees } from "./organization";

export const resources = pgTable("resources", { id: uuid("id").defaultRandom().primaryKey(), assetId: uuid("asset_id").references(() => assets.id), name: text("name").notNull(), type: text("type").notNull(), location: text("location").notNull() });
export const bookings = pgTable("bookings", { id: uuid("id").defaultRandom().primaryKey(), resourceId: uuid("resource_id").notNull().references(() => resources.id), bookedByEmployeeId: uuid("booked_by_employee_id").notNull().references(() => employees.id), departmentId: uuid("department_id").references(() => departments.id), startsAt: timestamp("starts_at", { withTimezone: true }).notNull(), endsAt: timestamp("ends_at", { withTimezone: true }).notNull(), status: bookingStatusEnum("status").notNull().default("upcoming"), createdAt: timestamp("created_at").defaultNow().notNull() }, (table) => [index("bookings_resource_starts_at_idx").on(table.resourceId, table.startsAt)]);
export const maintenanceRequests = pgTable("maintenance_requests", { id: uuid("id").defaultRandom().primaryKey(), assetId: uuid("asset_id").notNull().references(() => assets.id), raisedByEmployeeId: uuid("raised_by_employee_id").notNull().references(() => employees.id), issueDescription: text("issue_description").notNull(), priority: maintenancePriorityEnum("priority").notNull().default("medium"), photoUrl: text("photo_url"), status: maintenanceStatusEnum("status").notNull().default("pending"), reviewedByEmployeeId: uuid("reviewed_by_employee_id").references(() => employees.id), technicianName: text("technician_name"), createdAt: timestamp("created_at").defaultNow().notNull(), approvedAt: timestamp("approved_at"), resolvedAt: timestamp("resolved_at") });
export const auditCycles = pgTable("audit_cycles", { id: uuid("id").defaultRandom().primaryKey(), name: text("name").notNull(), scopeDepartmentId: uuid("scope_department_id").references(() => departments.id), scopeLocation: text("scope_location"), startDate: date("start_date").notNull(), endDate: date("end_date").notNull(), status: auditCycleStatusEnum("status").notNull().default("scheduled"), createdByEmployeeId: uuid("created_by_employee_id").notNull().references(() => employees.id) });
export const auditCycleAuditors = pgTable("audit_cycle_auditors", { auditCycleId: uuid("audit_cycle_id").notNull().references(() => auditCycles.id, { onDelete: "cascade" }), employeeId: uuid("employee_id").notNull().references(() => employees.id, { onDelete: "cascade" }) }, (table) => [primaryKey({ columns: [table.auditCycleId, table.employeeId] })]);
export const auditItems = pgTable("audit_items", { id: uuid("id").defaultRandom().primaryKey(), auditCycleId: uuid("audit_cycle_id").notNull().references(() => auditCycles.id), assetId: uuid("asset_id").notNull().references(() => assets.id), result: auditItemResultEnum("result").notNull().default("pending"), notes: text("notes"), checkedByEmployeeId: uuid("checked_by_employee_id").references(() => employees.id), checkedAt: timestamp("checked_at") });
export const notifications = pgTable("notifications", { id: uuid("id").defaultRandom().primaryKey(), employeeId: uuid("employee_id").notNull().references(() => employees.id), type: notificationTypeEnum("type").notNull(), message: text("message").notNull(), entityType: text("entity_type").notNull(), entityId: uuid("entity_id").notNull(), isRead: boolean("is_read").notNull().default(false), createdAt: timestamp("created_at").defaultNow().notNull() }, (table) => [index("notifications_employee_read_idx").on(table.employeeId, table.isRead)]);
export const activityLogs = pgTable("activity_logs", { id: uuid("id").defaultRandom().primaryKey(), actorEmployeeId: uuid("actor_employee_id").notNull().references(() => employees.id), action: text("action").notNull(), entityType: text("entity_type").notNull(), entityId: uuid("entity_id").notNull(), metadata: jsonb("metadata").notNull().default({}), createdAt: timestamp("created_at").defaultNow().notNull() });
